# Same as kubectl CLI command:
#
# kubectl expose deployment hello-web --type=NodePort --port=3080
#
apiVersion: v1
kind: Service
metadata:
  name: hello-web
spec:
  selector:
    app: hello-web
  type: NodePort
  ports:
  - port: 3080
