apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web
  labels:
    app: hello-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-web
  template:
    metadata:
      labels:
        app: hello-web
    spec:
      containers:
      - name: web
        image: nkuba/hello-web:2.4
        ports:
        - containerPort: 3080
        imagePullPolicy: Always
      - name: db
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: hello-web
spec:
  selector:
    app: hello-web
  type: NodePort
  ports:
  - port: 3080
    nodePort: 30080       #Expose the service on specific Node Port